import Foundation

@main struct FeatureChecks {
    static func main() async throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent("obby-feature-checks-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: root) }
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        let vault = Vault(root)
        try vault.mkdir("Science")
        try vault.mkdir("Attachments")
        try vault.write("Science/Plants.md", content: "# Photosynthesis\n\n## Light reactions\n\nChlorophyll captures sunlight to make energy.\n\n```swift\n# not a heading\n```\n\n## Carbon cycle\n\nPlants use carbon dioxide.", create: true)
        try vault.write("Science/History.md", content: "# History\n\nA history of old maps.", create: true)
        try vault.write("Attachments/Hidden.md", content: "chlorophyll secret", create: true)
        let index = NoteIndex()
        await index.rebuild(vault: vault)
        let found = await index.search("chlorophyll sunlight")
        precondition(found.first?.path == "Science/Plants.md")
        precondition(found.first?.heading.contains("Light reactions") == true)
        precondition(!found.contains { $0.path.contains("Attachments") })
        precondition(found.first?.text.contains("# not a heading") == true)
        precondition(found.first?.heading == "Photosynthesis › Light reactions")
        let attachments = await index.search("secret")
        precondition(attachments.isEmpty)
        try vault.write("Science/History.md", content: "# Chlorophyll guide\n\nSunlight is captured here.")
        await index.update(vault: vault, paths: ["Science/History.md"])
        let updated = await index.search("chlorophyll guide")
        precondition(updated.first?.path == "Science/History.md")
        try FileManager.default.removeItem(at: try vault.resolve("Science/History.md"))
        await index.update(vault: vault, paths: ["Science/History.md"])
        let deleted = await index.search("history")
        precondition(!deleted.contains { $0.path == "Science/History.md" })
        let excluded = await index.search("chlorophyll", excluding: ["Science/Plants.md"])
        precondition(excluded.isEmpty)
        // Repeated rebuilds preserve results, and updates re-read even with the same date.
        try vault.write("Science/Plants.md", content: "# Botany\n\nLeaves contain xylem.")
        await index.rebuild(vault: vault)
        let rebuilt = await index.search("xylem")
        precondition(rebuilt.first?.path == "Science/Plants.md")
        await index.rebuild(vault: vault)
        let unchanged = await index.search("xylem")
        precondition(rebuilt == unchanged)
        try vault.write("Science/Sections.md", content: "# Root\n### First\nalpha\n### Second\nbeta\n````\n```\n# falseheading\n````\n## Third\n" + String(repeating: "paragraph ", count: 500), create: true)
        await index.update(vault: vault, paths: ["Science/Sections.md"])
        let sibling = await index.search("beta")
        precondition(sibling.first?.heading == "Root › Second")
        let fenced = await index.search("falseheading")
        precondition(fenced.first?.heading == "Root › Second")
        let long = await index.search("paragraph", limit: 100)
        precondition(long.count == 2)
        precondition(long.allSatisfy { $0.text.count <= 1_200 })
        let empty = await index.search("the and", limit: 3)
        precondition(empty.isEmpty)
        let noLimit = await index.search("xylem", limit: 0)
        precondition(noLimit.isEmpty)
        let plantsURL = try vault.resolve("Science/Plants.md")
        let date = try plantsURL.resourceValues(forKeys: [.contentModificationDateKey]).contentModificationDate!
        try vault.write("Science/Plants.md", content: "# Botany\n\nPhloem transports sugars.")
        try FileManager.default.setAttributes([.modificationDate: date], ofItemAtPath: plantsURL.path)
        await index.update(vault: vault, paths: ["Science/Plants.md"])
        let forced = await index.search("phloem")
        precondition(forced.first?.path == "Science/Plants.md")
        try FileManager.default.removeItem(at: plantsURL)
        await index.rebuild(vault: vault)
        let removed = await index.search("phloem")
        precondition(removed.isEmpty)
        try vault.mkdir("Science/Attachments")
        try vault.write("Science/Attachments/Ignore.md", content: "excludedtoken", create: true)
        await index.update(vault: vault, paths: ["Science/Attachments/Ignore.md"])
        let nestedAttachment = await index.search("excludedtoken")
        precondition(nestedAttachment.isEmpty)
        try FileManager.default.createSymbolicLink(at: root.appendingPathComponent("Link.md"), withDestinationURL: root.appendingPathComponent("Science/Sections.md"))
        await index.update(vault: vault, paths: ["Link.md", "../outside.md", "/tmp/outside.md"])
        let safe = await index.search("beta", limit: 100)
        precondition(safe.allSatisfy { $0.path == "Science/Sections.md" })
        precondition(QuickAction.parse("/summarize save")?.action == .summarise)
        precondition(QuickAction.parse("/flashcards")?.save == false)
        precondition(QuickAction.parse("/revision SAVE")?.action == .revisionNotes)
        precondition(QuickAction.parse("please /quiz") == nil)
        let name = QuickAction.noteName(for: "Science/Plants.md", action: .flashcards, existing: ["Science/Plants Flashcards.md", "Science/Plants Flashcards 2.md"])
        precondition(name == "Science/Plants Flashcards 3.md")
        precondition(QuickAction.noteName(for: "Plants.md", action: .quiz, existing: []) == "Plants Quiz.md")
        precondition(QuickAction.parse("/quiz save extra") == nil)
        precondition(QuickAction.parse("/outline please") == nil)
        precondition(QuickAction.parse(" /QUIZ SAVE \n")?.save == true)
        precondition(QuickAction.instructionCheck)
        print("Feature checks passed")
    }
}

private extension QuickAction {
    static var instructionCheck: Bool {
        summarise.instruction.contains("5-8") && flashcards.instruction.contains("Q:") &&
        quiz.instruction.contains("Answers") && outline.instruction.contains("nested") &&
        revisionNotes.instruction.contains("headings")
    }
}
